version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  # zookeeper-1:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_SERVER_ID: 1
  #     ZOOKEEPER_CLIENT_PORT: 22181
  #     ZOOKEEPER_TICK_TIME: 2000
  #     ZOOKEEPER_INIT_LIMIT: 5
  #     ZOOKEEPER_SYNC_LIMIT: 2
  #     ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
  #   ports:
  #     - "22181:22181"
  #     - "22888:22888"
  #     - "23888:23888"

  # zookeeper-2:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_SERVER_ID: 2
  #     ZOOKEEPER_CLIENT_PORT: 32181
  #     ZOOKEEPER_TICK_TIME: 2000
  #     ZOOKEEPER_INIT_LIMIT: 5
  #     ZOOKEEPER_SYNC_LIMIT: 2
  #     ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
  #   ports:
  #     - "32181:32181"
  #     - "32888:32888"
  #     - "33888:33888"

  # zookeeper-3:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_SERVER_ID: 3
  #     ZOOKEEPER_CLIENT_PORT: 42181
  #     ZOOKEEPER_TICK_TIME: 2000
  #     ZOOKEEPER_INIT_LIMIT: 5
  #     ZOOKEEPER_SYNC_LIMIT: 2
  #     ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
  #   ports:
  #     - "42181:42181"
  #     - "42888:42888"
  #     - "43888:43888"

  # kafka-1:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper-1
  #     - zookeeper-2
  #     - zookeeper-3
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
  #   ports:
  #     - "19092:19092"

  # kafka-2:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper-1
  #     - zookeeper-2
  #     - zookeeper-3
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
  #   ports:
  #     - "29092:29092"

  # kafka-3:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper-1
  #     - zookeeper-2
  #     - zookeeper-3
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:22181,zookeeper-2:32181,zookeeper-3:42181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092
  #   ports:
  #     - "39092:39092"
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092
    ports:
      - "19092:19092"

  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092
    ports:
      - "29092:29092"

  kafka-3:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:39092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092
    ports:
      - "39092:39092"

  spark-master:
    image: bitnami/spark:latest
    hostname: spark-master
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-data:/bitnami

  spark-worker:
    image: bitnami/spark:latest
    hostname: spark-worker
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./spark-data:/bitnami

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  spark-data:
    driver: local
  redis-data:
    driver: local